create table MEMBER(
	MEMBER_ID VARCHAR2(20),
	MEMBER_PW VARCHAR2(15),
	MEMBER_NAME VARCHAR2(20),
	MEMBER_JUMIN1 INT,
	MEMBER_JUMIN2 INT,
	MEMBER_EMAIL VARCHAR2(25),
	MEMBER_EMAIL_GET VARCHAR2(7),
	MEMBER_MOBILE VARCHAR2(13),
	MEMBER_PHONE VARCHAR2(13),	
	MEMBER_ZIPCODE VARCHAR2(13),	
	MEMBER_ADDR1 VARCHAR2(70),
	MEMBER_ADDR2 VARCHAR2(70),
	MEMBER_ADMIN INT,
	MEMBER_JOIN_DATE DATE
);

create table ZIPCODE(
	ID INT
	ZIPCODE VARCHAR2(7),
	SIDO VARCHAR2(20),
	GUGUN VARCHAR2(13),
	DONG VARCHAR2(24),
	RI VARCHAR2(36),
	BUNJI VARCHAR2(17),
	PRIMARY KEY(ID)
);

create sequence zipcode_id_seq;

insert into zipcode 
vlaues(zipcode_id_seq.NEXTVAL,'123-456','서울','종로구','관철동','','13-13');

commit;